service: craftmate-ai-app
env: flex
entrypoint: gunicorn -b :8080 main:app
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  GCS_BUCKET_NAME: craftmate-ai
  ALLOWED_EXTENSIONS: jpg,jpeg,png
  BEARER_TOKEN: test
